version: '3.8'

services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    volumes:
      - "${CONFIG_VOLUME}:/opt/JDownloader/app/cfg"
      - "${DOWNLOADS_VOLUME}:/opt/JDownloader/Downloads"
      - "${LOGS_VOLUME}:/opt/JDownloader/app/logs" # Optional
      - "${EXTENSIONS_VOLUME}:/opt/JDownloader/app/extensions" # Optional
      - /etc/localtime:/etc/localtime:ro # Optional
    environment:
      MYJD_USER: "${MYJD_USER}" # Optional (email for MyJDownloader)
      MYJD_PASSWORD: "${MYJD_PASSWORD}" # Optional (password for MyJDownloader)
      MYJD_DEVICE_NAME: "${MYJD_DEVICE_NAME}" # Optional (device name for MyJDownloader)
      XDG_DOWNLOAD_DIR: "/opt/JDownloader/Downloads" # Optional
    ports:
      - "${JD_PORT_EXTERNAL}:3129"
    env_file:
      - .env
