---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Asia/Calcutta
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads #optional
    ports:
      - ${QBITTORENT_PORT}:8080
      - ${TORRENTING_PORT}:6881
      - ${TORRENTING_PORT}:6881/udp
    env_file:
      - .env
    restart: unless-stopped
