---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Asia/Calcutta
      - WEBUI_PORT=${QBITTORENT_PORT}
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads #optional
    ports:
      - ${QBITTORENT_PORT}:${QBITTORENT_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp
    env_file:
      - .env
    restart: unless-stopped
